# Generated by Django 4.1.7 on 2023-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_alter_chat_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(upload_to="", verbose_name="Аудио файл"),
                ),
                ("text", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["audio_file"],
            },
        ),
    ]
