"""
Django settings for django_chatbot project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wsa9k4v_goql%t8rn@q4*5flo+xnnxa%8!^p2g(4g-=py==ur)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Включите HTTPS, установив SECURE_PROXY_SSL_HEADER
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Укажите пути к сертификату и закрытому ключу SSL
SECURE_SSL_REDIRECT = True
SECURE_SSL_HOST = '80.72.180.130'  # Замените на ваш домен
SECURE_SSL_PROXY = True

# ...

# Только для разработки можно использовать самоподписанный сертификат
# Убедитесь, что вы заменили пути на правильные расположения файлов
SSL_CERTIFICATE_KEY = '/mnt/ks/Works/Chatbot/django_chatbot/django_site2.key'
SSL_CERTIFICATE = '/etc/ssl/certs/django_site2.crt'

# SSL_CERTIFICATE_KEY = '/mnt/ks/Works/ASR/ws/key.pem'
# SSL_CERTIFICATE = '/mnt/ks/Works/ASR/ws/cert.pem'


ALLOWED_HOSTS = ['80.72.180.130']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatbot',
    'constance',
    'constance.backends.database',
    'channels',
    'sslserver',
    'captcha',
]
RECAPTCHA_PUBLIC_KEY = '6LfYy4koAAAAABqNb5WjFTj68wkPxAkCpRmE85WC'
RECAPTCHA_PRIVATE_KEY = '6LfYy4koAAAAALfeWuJmhwL6AUIVMKlW9C0Vpr6v'

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_null_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (("Mistral", "Mistral"), ("Claudia", "Claudia"), ("Random", "Random"))
    }],
}
CONSTANCE_CONFIG = {
    'Model': ('Mistral', 'Select model', 'yes_no_null_select' ),
}
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

#CONSTANCE_REDIS_CONNECTION = 'redis://127.0.0.1:6000/0'  # Замените на ваши настройки Redis


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
ROOT_URLCONF = 'django_chatbot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'django_chatbot.wsgi.application'
ASGI_APPLICATION = 'django_chatbot.asgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ky'

TIME_ZONE = 'Etc/GMT-6'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT= os.path.join(BASE_DIR, 'static')

INTERNAL_IPS = [
    "127.0.0.1", '80.72.180.130'
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'